# Generated by Django 4.0.4 on 2022-05-01 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Movie Title')),
                ('release_date', models.TimeField(verbose_name='Release Date')),
                ('cover', models.CharField(max_length=250, verbose_name='Movie Url Cover')),
                ('cover1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Movie Url Cover1')),
                ('cover2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Movie Url Cover2')),
                ('trailer', models.CharField(max_length=250, verbose_name='Movie Url Trailer')),
                ('recap', models.TextField(verbose_name='Movie Recap')),
                ('fav', models.BooleanField(default=False, verbose_name='Favorite')),
                ('rete', models.FloatField(default=0, verbose_name='Movie Rate')),
                ('created_at', models.TimeField(auto_now=True, verbose_name='Movie created at')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
