# Generated by Django 4.0.4 on 2022-05-02 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('duration', models.FloatField(default=0, verbose_name='Duration in minutes')),
                ('cover', models.CharField(max_length=250, verbose_name='Url Cover')),
                ('cover1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url Cover1')),
                ('cover2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url Cover2')),
                ('trailer', models.CharField(max_length=250, verbose_name='Url Trailer')),
                ('recap', models.TextField(verbose_name='Recap')),
                ('fav', models.BooleanField(default=False, verbose_name='Favorite')),
                ('rate', models.FloatField(default=0, verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
        ),
    ]
